// These lines are the quotes the script will randomly choose. You can put as much as you want.
// Emulates the "Edit Quotes..." option in the original.
// If you absolutely need to put " inside your quotes, use either ' or \".
// You can add line breaks by adding <br> tags. You can put html codes in quotes but it's not recommended.
// Don't forget, the quotes have a , after the "" !!
const quotes = [
    // Original "Say What?" quotes
    "It has just been discovered that research causes cancer in rats.",
    "Pro is to con as progress is to Congress",
    "Sex is not the answer. Sex is the question. \"Yes\" is the answer.",
    "It is impossible to make anything foolproof because fools are so ingenious.",
    "Lubarsky's Law of Cybernetic Entomology:<br><br>There's always one more bug.",
    "Paul's Law:<br><br>You can't fall off the floor.",
    "Heller's Law:<br><br>The first myth of management is that it exists.",
    "First Law of Bicycling:<br><br>No matter which way you ride, it's uphill and against the wind.",
    "Osborn's Law:<br><br>Variables won't; constants aren't.", // except in JS!
    "Weinberg's Second Law:<br><br>If builders built buildings the way programmers wrote programs, then the first woodpecker that came along would destroy civilization.",
    "First Law of Socio-Genetics:<br><br>Celibacy is not hereditary.",
    "Parker's Law:<br><br>Beauty is only skin deep, but ugly goes clean to the bone.",
    "Hartley's First Law:<br><br>You can lead a horse to water, but if you can get him to float on his back, you've got something.",
    "Dentist:<br><br>A prestidigitator who, putting metal in one's mouth, pulls coins out of one's pockets.<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-- Ambrose Bierce",
    "Somebody ought to cross ball point pens with coat hangers so that the pens will multiply instead of disappear.",
    "While your friend holds you affectionately by both your hands you are safe, for you can watch both of his.",
    "You don't have to think too hard when you talk to teachers.<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-- J.D. Salinger",
    "If bankers can count, how come they have eight windows and only four tellers?",
    "Those who can't write, write manuals.",
    "Never call a man a fool. Borrow from him.",
    "A truly wise man never plays leapfrog with a unicorn.",
    "\"He was so narrow minded he could see through a keyhole with both eyes...\"",
    "The average woman would rather have beauty than brains, because the average man can see better than he can think.",
    "You have the capacity to learn from mistakes. You'll learn a lot today.",
    "You worry too much about your job. Stop it. You are not paid enough to worry.",
    "The brain is a wonderful organ: it starts working the moment you get up in the morning, and does not stop until you get to school.",
    "Paranoids are people, too; they have their own problems. It's easy to criticize, but if everybody hated you, you'd be paranoid too.",
    "I'd give my right arm to be ambidextrous.",
    "Nudists are people who wear one-button suits.",
    "Main's Law:<br><br>For every action there is an equal and opposite government program.",
    "Pohl's Law:<br><br>Nothing is so good that somebody, somewhere, will not hate it.",
    "Diplomacy is the art of saying \"nice doggy\" until you can find a rock.",
    "If you don't care where you are, then you aren't lost.",
    "Consultants are mystical people who ask a company for a number and then give it back to them.",
    "Duct tape is like the Force. It has a light side, and a dark side, and it holds the universe together.",
    "Insanity is hereditary. You get it from your kids.",
    "Scott's first Law:<br><br>No matter what goes wrong, it will probably look right.",
    "The new congressmen say they're going to turn the government around. I hope I don't get run over again.",
    "About the time we make ends meet, somebody moves the ends.",
    "God made the Idiot for practice, and then He made the School Board.<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-- Mark Twain",
    "Be wary of strong drink. It can make you shoot at tax collectors and miss.",
    "Dying is a very dull, dready affair. And my advice to you is to have nothing whatever to do with it.<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-- W. Somerset Maugham",
    "It is easier to change the specification to fit the program than vice versa.",
    "Stealing a rhinoceros should not be attempted lightly.",
    "All I ask is a chance to prove that money can't make me happy.",
    "\"If you can count your money, you don't have a billion dollars.\"<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-- J. Paul Getty",
    "If you think nobody cares you're alive, try missing a couple of car payments.",
    "TV is chewing-gum for the eyes.<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-- Frank Lloyd Wright",
    "I used to think I was indecisive, but now I'm not so sure.",
    "Armadillo:<br><br>To provide weapons to a Spanish pickle.",
    "Micro Credo:<br><br>Never trust a computer bigger than you can lift.",
    "One nice thing about egotists: they don't talk about other people.",
    "There are three ways to get something done: do it yourself, hire someone, or forbid your kids to do it.",
    "How come wrong numbers are never busy?",
    "One way to stop a runaway horse is to bet on him.",
    "Serving coffee on aircraft causes turbulence.",
    "Eighty percent of all people consider themselves to be above average drivers.",
    "You never really learn to swear until you learn to drive.",
    "Misfortune:<br><br>The kind of fortune that never misses.",
    "Frisbeetarianism:<br><br>The belief that when you die, your soul goes up on the roof and gets stuck.",
    "When you are in it up to your ears, keep your mouth shut.",
    "A diplomat is someone who can tell you to go to hell and make you feel happy to be on your way.",
    "Ginsberg Theorem:<br><br><ol><li>You can't win.</li><li>You can't break even.</li><li>You can't even quit the game.</li></ol>",
    "Iron Law of Distribution:<br><br>Them that has, gets.",
    "Boob's Law:<br><br>You always find something in the last place you look.",
    "Weiler's Law:<br><br>Nothing is impossible for the man who doesn't have to do it himself.",
    "Hartley's Second Law:<br><br>Never sleep with anyone crazier than yourself.",
    "If you pick up a strarving dog and make him prosperous, he will not bite you. This is the principal difference between a dog and a man.<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-- Mark Twain",
    "Nothing astonishes men so much as common sense and plain dealing.",
    "Yield to temptation....it may not pass your way again.<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-- Lazarus Long",
    "Clothes make the man. Naked people have little or no influence on society.<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-- Mark Twain",
    "Blessed are they who go Go Around in Circles, for they Shall be Known as Wheels.",
    "There are four kinds of homicide: felonious, excusable, justifiable, and praiseworthy...<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-- Ambrose Bierce",
    "Children seldom misquote you. In fact, they usually repeat word for word what you shouldn't have said.",
    "I really hate this damned machine<br><br>I wish that they would sell it.<br><br>It never does quite what I want<br><br>But only what I tell it.",
    "Things are more like they used to be than they are now.",
    "Idiot:<br><br>A member of a large and powerful tribe whose influence in human affairs has always been dominant and controlling.",
    "Slick's Third Law of the Universe:<br><br>There are two types of dirt ---<br><ul><li>The dark kind, which is attracted to light objects, and</li><li>The light kind, which is attracted to dark objects.</li></ul>",
    "Faith is the quality that enables you to eat blackberry jam on a picnic without looking to see whether the seeds move.",
    "Fashion is a form of ugliness so intolerable that we have to alter it every six months.",
    "Important letters which contain no errors will develop errors in the mail. Corresponding errors will show up in the duplicate while the Boss is reading it.",
    "Vital papers will demonstrate their vitality by spontaneously moving from where you left them to where you can't find them.",
    "Velilind's Law of Experimentation:<br><br><ol><li>If reproducibility may be a problem, conduct the test only once.</li><li>If a straight line fit is required, obtain only two data points.</li></ol>",
    "Colvard's Logical Premise:<br><br>All probabilities are 50%. Either a thing will happen or it won't.",
    "If you put garbage in a computer nothing comes out but garbage. But this garbage, having passed through a very expensive machine, is somehow ennobled and none dare criticize it.",
    "The IQ of the group is the lowest IQ of a member of the group divided by the number of people in the group.",
    "Worst vegetable of the year: the brussels sprout.<br><br>This is also the worst vegetable of next year.",
    "It's not that I'm afraid to die. I just don't want to be there when it happens.<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-- Woody Allen",
    "I have seen the future and it is just like the present, only longer.<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-- Kehlog Albran",
    "There has been an alarming increase in the number of things you know nothing about.",
    "What makes the universe so hard to comprehend is that there's nothing to compare it with.",
    "It may be that your whole purpose in life is simply to serve as a warning to others.",
    "Yesterday I was a dog. Today I'm a dog. Tomorrow I'll probably still be a dog. Sigh! There's so little hope for advancement.<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-- Snoopy",
    "The trouble with being poor is that it takes up all your time.",
    "AMAZING BUT TRUE...<br><br>There is so much sand in Northern Africa that if it were spread out it would completely cover the Sahara desert.",
    "Anyone who is capable of getting themselves made President should on no account be allowed to do the job.<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-- The Hitchhiker's Guide to the Galaxy",
    "SEMINARS: from 'semi' and 'arse', hence, any half-assed discussion.",
    "The trouble with doing something right the first time is that nobody appreciates how difficult it was.",
    "Law of Probable Dispersal:<br><br>Whatever it is that hits the fan will not be evenly distributed.",
    "Murphy's Law is recursive. Washing your car to make it rain doesn't work.",
    "Rule of Defactualization:<br><br>Information deteriorates upward through bureaucracies.",
    "...It has been observed that one's nose is never so happy as when it is thrust into the affairs of another, from which some physiologists have drawn the inference that the nose is devoid of the sense of smell.",
    "Hofstadter's Law:<br><br>It always takes longer than you expect, even when you take Hofstadter's Law into account.",
    "Prewdhomme's Law of Window Cleaning:<br><br>It's on the other side.",
    "Zymurgy's Law of Volunteer Labor:<br><br>People are always available for work in the past tense.",
    "Ninety-Ninety Rule of Project Schedules:<br><br>The first ninety percent of hte task takes ninety percent of the time, and the last ten percent takes the other ninety percent.",
    "Canada Bill Jones' Motto:<br>&nbsp;&nbsp;It's morally wrong to allow suckers to keep their money.<br><br>Supplement:<br>&nbsp;&nbsp;A .44 magnum beats four aces.",
    "Jone's Motto:<br><br>Friends come and go, but enemies accumulate.",
    "Cole's Law: Thinly sliced cabbage.",
    "A classic is something that everybody wants to have read, and nobody wants to read.<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-- Mark Twain",
    "NAPOLEON: What shall we do with this soldier, Guiseppe? Everything he says is wrong.<br><br>GUISEPPE: Make him a general, Excellency, and then everything he says will be right.<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-- G. B. Shaw",
    "\"Hey, who took the cork off my lunch??!\"<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-- W. C. Fields",
    "Good news. Ten weeks from Friday will be a pretty good day.",
    "Drive defensively. Buy a tank.",
    "Philadelphia is not dull -- it just seems so because it is next to exciting Camden, New Jersey.",
    "Minnie Mouse is a slow maze learner.",
    "Conway's Law:<br><br>In any organization there will always be one person who knows what is going on.<br><br>This person must be fired.",
    "Fourth Law of Applied Terror:<br>The night before the English History mid-term, your Biology instructor will assign 200 pages on planaria.<br><br>Corollary:<br>Every instructor assumes that you have nothing else to do except study for that instructor's class.",
    "Fifth Law of Applied Terror:<br>If you are givent an open-book exam, you will forget your book.<br><br>Corollary:<br>If you are given a take-home test, you will forget where you live.",
    "Just because your doctor has a name for your condition doesn't mean he knows what it is.",
    "Nothing is faster than the speed of light...<br><br>To prove this to yourself, try opening the refrigerator door before the light comes on.",
    "Even the best of friends cannot attend each other's funeral.<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-- Kehlog Albran",
    "Anything is good if it's made of chocolate.",
    "The marvels of today's modern technology include the development of a soda can which, when discarded, will last forever....and a $15,000 car which, when properly cared for, will rust out in two or three years.",
    "\"Wagner's music is better than it sounds.\"<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-- Mark Twain",
    "Leibowitz's Rule:<br><br>When hammering a nail, you will never hit your finger if you hold the hammer with both hands.",
    "Goldenstern's Rules:<br><br><ol><li>Always hire a rich attorney.</li><li>Never buy from a rich salesman.</li></ol>",
    "Weiner's Law of Libraries:<br><br>There are no answers, only cross references.",
    "You can always tell a Harvard man, but you can't tell him much.<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-- attributed to James Barnes",
    "Alimony and bribes will engage a large share of your wealth.",
    "Always remember to pillage BEFORE you burn.",
    "Murphy's Statement of the Power of Negative Thinking:<br><br>It is impossible for an optimist to be pleasantly surprised.",
    "Farnsdick's Corollary to the Fifth Corollary:<br><br>After things have gone from bad to worse, the cycle will repeat itself.",
    "FEATURE n. A surprising property of a computer program. A bug can be changed to a feature by documenting it.",
    "Having children is hereditary:<br><br>If your parents didn't have any, then you probably won't either.",
    "In a single day, Samson slew a thousand Philistines with the jawbone of an ass. Every day, thousands of sales are killed with the same weapon.",
    "Cheop's Law:<br><br>Nothing EVER gets built on schedule or within budget.",
    "Everything in excess! To enjoy the flavour of life, take big bites.<br>Moderation is for monks.<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-- Lazarus Long",
    "Never appeal to a man's \"better nature.\" He may not have one.<br>Invoking his self-interest gives you more leverage.<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-- Lazarus Long",
    "In a mature society, \"civil servant\" is semantically equal to \"civil master\".<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-- Lazarus Long",
    "Taxes are not raised for the benefit of the taxed.<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-- Lazarus Long",
    "Never underestimate the power of human stupidity.<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-- Lazarus Long",
    "Money is truthful. If a man speaks of his honor, make him pay cash.<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-- Lazarus Long",
    "The difference between science and the fuzzy subjects is that science requires reasoning, while those other subjects merely require scholarship.<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-- Lazarus Long",
    "A committee is a life form with six or more legs and no brain.<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-- Lazarus Long",
    "The Law of Frisbee:<br><br>The most powerful force in the world is that of a disc straining to land under a car, just out of reach (this force is technically termed \"car suck\").",
    "You must realize that the computer has it in for you. The irrefutable proof of this is that the computer always does what you tell it to do.",
    "Putt's Law:<br><br>Technology is dominated by two types of people:<br><ol><li>Those who understand what they do not manage.</li><li>Those who manage what they do not understand.</li></ol>",
    "Mr. Cole's Axiom:<br><br>The sum of the intelligence on the planet is a constant; yet the population is growing.",
    "Mosher's Law of Software Engineering:<br><br>Don't worry if it doesn't work right. If everything did, you'd be out of a job.",
    "Two can live as cheaply as one of half as long.",
    "In our civilization, and under our republican form of government, intelligence is so highly honored that it is rewarded by exemption from the cares of office.",
    "You may have heard that a dean is to faculty as a hydrant is to a dog.<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;--- Alfred Kahn",
    "Show respect for age. Drink good scotch for a change.",
    "How long a minute is depends upon which side of the bathroom door you're on.",
    "One reason why computers can do more work than people is that they never have to stop and answer the phone.",
    "At the source of every error which is blamed on the computer, you will find at least two human errors, including the error of blaming it on the computer.",
    "Electrical Engineers do it with less resistance.",
    "Psychiatrists say that one out of four people are mentally ill. Check three friends. If they're ok, you're it.",
    "You are only young once, but you can stay immature indefinitely.",
    "If you want your spouse to listen and pay strict attention to every word you say, talk in your sleep.",
    "People usually get what's coming to them .... unless it's been mailed.",
    "Oliver's Law:<br><br>Experience is something you don't get until jsut after you need it.",
    "Slick's First Law of the Universe:<br><br>Nothing in the known universe travels faster than a bad check.",
    "Slick's Second Law of the Universe:<br><br>A quarter-ounce of chocolate = four pounds of fat.",
    "You know it's going to be a bad day when...<br><br>You want to put on the clothes that you wore home from the party and there aren't any.",
    "Finagle's Third Law:<br><br>In any collection of data, the figure most obviously correct, beyond all need of checking, is the mistake.",
    "You know it's going to be a bad day when...<br><br>Your blind date turns out to be your ex-wife.",
    "I like work...<br><br>I can sit and watch it for hours.",
    "Too much of a good thing is WONDERFUL.<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-- Mae West",
    "You will be a winner today. Pick a fight with a four-year-old.",
    "REPORTER (to Mahatma Gandhi): Mr Gandhi, what do you think of Western Civilization?<br><br>GANDHI: I think it would be a good idea.",
    "The way to make a small fortune in the commodities market is to start with a large fortune.",
    "How many hardware engineers does it take to change a light bulb?<br><br>None: \"We'll fix it in software.\"",
    "Meader's Law:<br><br>Whatever happens to you, it will previously have happened to everyone you know, only more so.",
    "Mitchell's Law of Committees:<br><br>Any simple problem can be made insoluble if enough meetings are held to discuss it.",
    "You know it's going to be a bad day when...<br><br>You wake up face down on the pavement.",
    "You know it's going to be a bad day when...<br><br>You put your bra on backwards and it fits better.",
    "You know it's going to be a bad day when...<br><br>Your birthday cake collapses from the weight of the candles.",
    "You know it's going to be a bad day when...<br><br>Your car horn goes off accidentally and remains stuck as you follow a group of Hell's Angels on the freeway.",
    "You know it's going to be a bad day when...<br><br>Your twin sister forgot your birthday.",
    "You know it's going to be a bad day when...<br><br>You wake up and discover that your waterbed sprang a leak, and then you realize that you don't have a waterbed.",
    "You know it's going to be a bad day when...<br><br>You see a \"60 Minutes\" news team waiting in your office.",
    "Originality is the art of concealing your source.<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-- Franklin P. Jones",
    "Perkin's Postulate:<br><br>The bigger they are, the harder they hit.",
    "Amand's Law of Management:<br><br>Everyone is always someplace else.",
    "Paul's Second Law:<br><br>The sooner you fall behind, the more time you will have to catch up.",
    "Seeger's Law:<br><br>Anything in parenthesis can be ignored.",
    "First Law of Corporate Planning:<br><br>Anything that can be changed will be changed until there is no time left to change anything.",
    "A crisis is when you can't say \"Let's forget the whole thing.\"",
    "Nash's Law:<br><br>Progress may have been all right once, but it went on too long.",
    "If you have a difficult task, give it to someone lazy ... that person will find an easier way to do it.",
    "Life is like a dog sled team ... if you ain't the lead dog, the scenery never changes.",
    "If there's artificial intelligence, there's bound to be some artificial stupidity.",
    "PROGRAM:<br><br>n. A magic spell cast over a computer allowing it to turn one's input into error messages.<br><br>tr.v. To engage in a pastime similar to banging one's head against a wall, but with fewer opportunities for reward.",

    // Additionnal quotes of my own
    "Ceci n'est pas une pipe.<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-- Magritte",
    "Keep love in your heart. A life without it is like a sunless garden when the flowers are dead.<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-- Oscar Wilde",
    "The most difficult thing is the decision to act, the rest is merely tenacity. The fears are paper tigers. You can do anything you decide to do. You can act to change and control your life; and the procedure, the process is its own reward.<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-- Amelia Earhart",
    "Love isn't something you find. Love is something that finds you.<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-- Loretta Young",
    "Good judgment comes from experience, and a lot of that comes from bad judgment.<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-- Will Rogers",
    "Honesty is the first chapter in the book of wisdom.<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-- Thomas Jefferson",
    "Today you are you! That is truer than true! There is no one alive who is you-er than you!<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-- Dr. Seuss",
    "Success is not final, failure is not fatal: it is the courage to continue that counts.<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-- Winston Churchill",
    "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-- Helen Keller",
    "It is during our darkest moments that we must focus to see the light.<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-- Aristotle",
    "Strange women lying in ponds, distributing swords, is no basis for a system of government!<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-- Monty Python's Holy Grail",
    "Are you suggesting that coconuts migrate?<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-- Monty Python's Holy Grail",
    "In a world without gold, we might've been heroes.<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-- Blackbeard",
    "What fun is there in making sense?<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-- Discord",
    "The only thing we're allowed to believe is that we won't regret the choice we made.<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-- Hajime Isayama",
    "So many books, so little time.<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-- Frank Zappa",
    "You only live once, but if you do it right, once is enough.<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-- Mae West",
    "Always forgive your enemies; nothing annoys them so much.<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-- Oscar Wilde",
    "No one can change a person, but a person can be the reason someone changes.<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-- SpongeBob SquarePants",
    "I find television very educating. Every time somebody turns on the set, I go into the other room and read a book.<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-- Groucho Marx",
    "Be nice to nerds. You may end up working for them. We all could.<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-- Charles J. Sykes",
    "Fighting for peace is like screwing for virginity.<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-- George Carlin",
    "A friend is someone who knows all about you and still loves you.<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-- Elbert Hubbard",
    "Any fool can know. The point is to understand.<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-- Albert Einstein",
    "I can calculate the motion of heavenly bodies but not the madness of people.<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-- Isaac Newton",
    "Opinion is really the lowest form of human knowledge. It requires no accountability, no understanding. The highest form of knowledge… is empathy, for it requires us to suspend our egos and live in another’s world. It requires profound purpose larger than the self kind of understanding.<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-- Bill Bullard",
    "Music expresses that which cannot be put into words and that which cannot remain silent”<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-- Victor hugo",
    "What a strange thing!<br>to be alive<br>beneath cherry blossoms.<br><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-- Kobayashi Issa",
];
